### ISSUE TITLE
Add assets for `09_conditions_intro`

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/draft_suso_course#24]
## Roadmap

- [x] Add roadmap: What do conditions do, Enabling conditions, Validation conditions, Filter conditions, Syntax, Variables

## What do conditions do

- [x] Copy assets from ZIM

## Enabling conditions

- [x] What they do. Copy from ZIM
- [x] Where to put them. Copy conditions example from ZIM and re-record
- [x] Where they work. Copy from ZIM for now. Consider re-recording for the future.
- [x] How SuSo conditions differ
  - [x] Fix typo in title
  - [x] Copy assets
- [x] How SuSo conditions differ. When evaluated. Re-record so no ZIMSTAT conditions title

## Filter conditions

- [x] What they do. Demo on the tablet
- [x] Where to put them. Demo on Designer.
- [x] How they work. Create slide by reusing earlier assets, just as in enabling conditions section.
- [x] Where they work. Create slide

## Validation conditions

- [x] What they do. Copy from ZIM
- [x] Where to put them. Copy conditions example from ZIM and re-record
- [x] How they work. Copy from ZIM
- [x] Where they work. Copy from ZIM for now. Consider re-recording for the future.
- [x] How SuSo  differs. Copy from ZIM
- [x] Comments. Add C# syntax highlighting, if possible

Optional. Not done for ZIM training. Simply copied qnr from SuSo docs.

- [x] Commands in general. Add C# syntax highlighting, if possible
- [x] Categorical: single-select. Relational. Find an other (specify) example in CWM qnr.
- [x] Categorical: single-select. InRange. Find a skip where enabled only for a continuous range of values in CWM qnr.
- [x] Categorical: single-select. InList. Find a skip where enabled only for a discontinuous set of values in CWM qnr.

## Variables

- [x] What is a variable. Consider adding images that are revealed along with their supporting bullet
- [x] Why use a variable. Consider adding images that are revealed along with their supporting bullet.
- [x] How to create. Re-record so do not see ZIMSTAT conditions title. Also, consider more examples.

## Worked example

- [x] Replicate ZIM's NFE example with CWM. See S5A and S5B.
